name: release
on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: "bash ci/release.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
